### ISSUE TITLE
Config loading issue

### ISSUE THREAD

**Issue by pawank** [outr/scarango#21]
My play framework 2.8 config in the application.conf looks like

```
arango {
    db = "_system"
    url =  "http://localhost:8529"
    authentication = true
    credentials {
      username = "root"
      password = "root"
    }
  }
```

SBT lib dependency is 
"com.outr" %% "scarango-driver" % "2.4.2"

ERROR:
```
Caused by: java.lang.RuntimeException: Failed to decode from {
  
}
        at com.outr.arango.ArangoDB$.config(ArangoDB.scala:100)
        at com.outr.arango.ArangoDB$.$lessinit$greater$default$1(ArangoDB.scala:17)
        at controllers.SignInController.$anonfun$view$1(SignInController.scala:38)
        at com.mohiva.play.silhouette.api.actions.UnsecuredActionBuilder.$anonfun$invokeBlock$6(UnsecuredAction.scala:152)
        at com.mohiva.play.silhouette.api.actions.UnsecuredRequestHandlerBuilder.$anonfun$invokeBlock$1(UnsecuredAction.scala:70)
        at scala.concurrent.impl.Promise$Transformation.run(Promise.scala:433)
        at scala.concurrent.BatchingExecutor$AbstractBatch.runN(BatchingExecutor.scala:134)
        at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:163)
        at scala.concurrent.BatchingExecutor$AsyncBatch.apply(BatchingExecutor.scala:146)
        at scala.concurrent.BlockContext$.usingBlockContext(BlockContext.scala:107)
```

I had tried directly giving the config parameters in the code like below
```
def view = UnsecuredAction.async { implicit request: Request[AnyContent] =>
    import com.outr.arango.api.{ OperationType, WALOperation, WALOperations }
    import com.outr.arango.{ ArangoDB, Credentials, DatabaseState }
    import io.youi.http.Headers
    val db = new ArangoDB(database = "_system", credentials = Some(Credentials("root", "root")))
    db.init().map { state =>
      println(state.toString.equalsIgnoreCase(DatabaseState.Initialized.toString()))
      println(db.session.client.request.headers.first(Headers.Request.Authorization))
    }
    Future.successful(Ok(signIn(SignInForm.form, socialProviderRegistry)))
  }
```

Can you please tell why the config is not getting picked? Anything else I need to do?
I am stuck at this point now.

**Comment by darkfrog26** [comment]
Scarango doesn't use Typesafe Config, it uses Profig. You need to run `Profig.initConfiguration()` or `Profig.initConfigurationBlocking()` in order to load configuration data from files. Your HOCON config should be picked and work just fine as-is though.

**Comment by pawank** [comment]
@darkfrog26 Worked thanks
