### ISSUE TITLE
Exception when trying to login

### ISSUE THREAD

**Issue by dirceusemighini** [outr/scarango#5]
Hello,
I'm following the project readme in arango version 3.2 and when I call 
Database.init() method it does throw the following exception.
I've tested it with a browser REST and the arango seems to be working fine, probably this is a circe parsing exception of the response.

URL: http://localhost:8529/_open/auth (Method: POST, Status: HttpResponseStatus(500: Attempt to decode value on failed cursor: DownField(must_change_password))),
Request: {
  "username" : "root",
  "password" : "password"
},
Response: {"jwt":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE1MDMzNDQyMDcsImlhdCI6MS41MDA3NTIyMDc0MTIyMDVlKzYsImlzcyI6ImFyYW5nb2RiIiwicHJlZmVycmVkX3VzZXJuYW1lIjoicm9vdCJ9.aZ-OFyZf2m2z9FeomDb-IognHKGsbIvEgYj5SGT-wqI="}
	at com.outr.arango.Arango.$anonfun$defaultErrorHandler$1(Arango.scala:33)
	at io.youi.client.HttpClient.$anonfun$restful$1(HttpClient.scala:143)
	at scala.util.Success.$anonfun$map$1(Try.scala:251)
	at scala.util.Success.map(Try.scala:209)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:287)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:29)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:29)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at scala.concurrent.impl.ExecutionContextImpl$AdaptedForkJoinTask.exec(ExecutionContextImpl.scala:140)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPProductInfoDb.init()ool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: DecodingFailure(Attempt to decode value on failed cursor, List(DownField(error)))

Any workaround on this?

**Comment by darkfrog26** [comment]
I haven't done any testing with 3.2 yet. Do you know if this was removed in 3.2 or something?

**Comment by darkfrog26** [comment]
PR merged. Feel free to submit another PR if you find any other issues with 3.2.  I'm planning on beginning the migration within the week myself.
